#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    low=0
    high=0
    mi = scores[0]
    ma = scores[0]
    for i in scores:
        if i>ma:
            high+=1
            ma=i
        elif i<mi:
            low+=1
            mi=i
    a = [high,low]
    return a   
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
