#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    x=0
    y=0
    for i in range(3):
        v1 = a[i]
        v2 = b[i]
        if v1>v2:
            x = x+1
        if v1<v2:
            y=y+1
        else:
            continue
    lt = [x,y]
    return lt
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
