#!/bin/python3

import os
import sys

#
# Complete the pageCount function below.
#
def pageCount(n, p):
    fr =p
    end = n-p
    if fr>end:
        x = end//2
    else:
        x = fr//2
    
    if n%2==0 and p==n-1:
        x=1
    if n==2 and p==1:
        x=0
    return x


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
