#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    base =0
    b=[]
    val=0
    for i in range(n):
        if s[i]=='U':
            base+=1
        if s[i]=='D':
            base-=1
        b.append(base)
        if b[i]<0 and b[i-1]>=0:
            val+=1
    if s[0]=='D':
        val+=1
    return val
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
