#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    l = len(arr)
    p=0;n=0;z=0
    for i in range(l):
        if arr[i] > 0:
            p = p+1
        if arr[i] == 0:
            z=z+1
        if arr[i] < 0:
            n=n+1
    print("{0:.6f}".format(p/l))
    
    print(round(n/l,6))
    
    print("{0:.6f}".format(z/l))
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
