#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    for i in range(1,n):
        for j in range(i,n):
            print(" ", end = '')
        for j in range(i):
            print("#", end = '')
        print()
    for i in range(n):
        print("#", end ='')
if __name__ == '__main__':
    n = int(input())

    staircase(n)
